### ISSUE TITLE
Error running the data prep script

### ISSUE THREAD

**Issue by oscarchanggoogle** [facebookresearch/muavic#8]
First, I downloaded lrs3_pretrain.zip, lrs3_test_v0.4.zip, and lrs_3_v0.4_txt.zip, and made sure the checksums matched. Unzipping them gave me three folders: pretrain, lrs3_v0.4, and test. I copied out lrs3_v0.4/trainval and placed it in the root folder beside pretrain.

Next, I ran the command:
python3 get_data.py --root-path . --src-lang en

I got an error with "Creating AVSR manifests for `en`"
KeyError: 'iW4fCwfw1vg/00033'

Can you please let me know I'm doing wrong?

**Comment by Anwarvic** [comment]
Hi @oscarchanggoogle,

Thanks for raising this issue!

Could you post the whole error trace so we can have a better understanding of what could've gone wrong?

**Comment by Anwarvic** [comment]
Hi @oscarchanggoogle 

Thank you for posting the full error trace! From the uploaded image, you can see that the `trainval` set hasn't been processed (attached below for your reference):

![image](https://user-images.githubusercontent.com/15960959/231924950-f3e4454b-9486-4993-933a-82c6c3928777.png)

Please, make sure that the `/usr/local/google/home/oscarchang/Downloads/muavic/lrs3/trainval` directory contains both txt files (`*.txt`) and videos (`*.mp4`).

My guess is that you didn't download the `trainval` data, you only downloaded the text `lrs_3_v0.4_txt.zip`. If that is the case, please download the set the same way you did with `pretrain.zip`, uncompress it inside `/usr/local/google/home/oscarchang/Downloads/muavic/lrs3` directory, and re-run the `get_data.py` script as you did earlier. The script should ignore all already-processed files and process only the new ones.

Hope this helps!

**Comment by Anwarvic** [comment]
Hi @oscarchanggoogle ,

Sorry to hear that you still having issues!

This error indicates that there is an audio file with the name `iW4fCwfw1vg/00018.wav` inside `~/Downloads/muavic/muavic/en/audio/train` directory. Could you please check if this audio file exists?

If yes, then something went wrong in the segmentation. The original file located in `~/Downloads/muavic/lrs3/pretrain/iW4fCwfw1vg/00018.mp4` should be segmented into `~Downloads/muavic/seg_pretrain/iW4fCwfw1vg/00018_{0,1,2,3,4}.mp4`. And then later the audio is extracted and written to `~Downloads/muavic/muavic/en/audio/train/iW4fCwfw1vg/00018_{0,1,2,3,4}.wav`.

 So, I would suggest delete the audio file `~/Downloads/muavic/lrs3/pretrain/iW4fCwfw1vg/00018.wav` and the video file `~/Downloads/muavic/lrs3/pretrain/iW4fCwfw1vg/00018.mp4` and re-run the script.

Due to the nature of your issue, it is so hard to replicate. So, probably we are going to go back and forth multiple times in order to resolve this issue. So, kindly plan accordingly!
